### ISSUE TITLE
TypeError: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt

### ISSUE THREAD

**Issue by maumercado** [dcodeIO/endecrypt#1]
Im getting this error while decrypting an encrypted value saved on the db, Im using node 0.10.28.

Ive been getting this error when I changed from ubuntu to smartOS, Im not sure if that has anything to do with it.

Im running this command 

App.Utils.endecrypt.decrypt(valuep.reverse(), readfile, {rounds:2}, function (err, dec){ console.log(err);})

and this to encrypt

App.Utils.endecrypt.encrypt(attrBuffer, data, {rounds: 2}, function (err, enc) {})

**Comment by dcodeIO** [comment]
This error is usually thrown when the provided key is incorrect. If it is definitively correct, this could also be some sort of incompatibility that I am not yet aware of. Hope it isn't the latter.

Other resources also mention [incompatible padding](https://github.com/nodejs/node/issues/2794) as a cause.

**Comment by maumercado** [comment]
Defintely an incorrect key.

**Comment by doomsbuster** [comment]
You saved my day. There are several posts that give code solutions but none of them explained when this error typically occurs. @dcodeIO thank you for this explanation.

**Comment by mapleshawxiao** [comment]
`let iv = "";
let cipher = crypto.createCipheriv(algorithm, key, iv);`
maybe u can try this, add a vector, if u are using nodejs

**Comment by godblesshugh** [comment]
got the same problems here, any further solution plz?

**Comment by gjunming** [comment]
https://github.com/nodejs/node/issues/2794 this is a solution to fix

**Comment by godblesshugh** [comment]
thx, already use `.setAutoPadding(false);`

**Comment by aliciafraguasrubio** [comment]
Another incorrect key here, thank you for the explanation!

**Comment by sergio-domingues** [comment]
incorrect key or incorrect ciphered data
